version: "3.9"

services:
  web:
    build: .
    ports:
      - "8080:8080"
  prometheus:
    ports:
      - "9090:9090"
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
